name: Delete package

on:
  workflow_dispatch:
    inputs:
      VERSION_IDS:
        description: "Package version IDs"
        default: ""
      REPO:
        description: "Repo hosting the package"
        default: ""
      NAME:
        description: "Package name"
        default: ""
      NUM:
        description: "The number of old versions to delete"
        default: "1"

jobs:
  delete:
    runs-on: windows-latest

    steps:
    - uses: actions/delete-package-versions@v1
      with:
        package-version-ids: '${{ github.event.inputs.VERSION_IDS }}'
        repo: '${{ github.event.inputs.REPO }}'
        package-name: '${{ github.event.inputs.NAME }}'
        num-old-versions-to-delete: '${{ github.event.inputs.NUM }}'
        token: ${{ secrets.GITHUB_TOKEN }}
